services:
  - type: web
    name: telegram-youtube-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python youtube_bot.py
    pythonVersion: 3.11
